name: zotoapp
description: A mini chat application with WebSocket and Riverpod
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  intl: ^0.20.2

  # Network
  http: ^1.1.0

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7

flutter:
  uses-material-design: true